/**
 * NDMO Massive Realistic Data Seed Script
 * Based on real Saudi Arabia data breach incidents from 2012-2026
 * Sources: CYFIRMA, Cyberlands, Resecurity, CyberNews, BBC, Al Jazeera, DarkReading
 */
// ============================================================
// LEAKS — 45 realistic Saudi data breach records
// ============================================================

export const leaks = [
  // === CRITICAL SEVERITY ===
  {
    leakId: "LK-2024-0001",
    title: "Saudi Ministry of Foreign Affairs Employee Database Breach",
    titleAr: "اختراق قاعدة بيانات موظفي وزارة الخارجية السعودية",
    source: "darkweb",
    severity: "critical",
    sector: "Government",
    sectorAr: "حكومي",
    piiTypes: JSON.stringify(["National ID", "Full Name", "Phone", "Email", "Job Title"]),
    recordCount: 1400000,
    status: "reported",
    description: "On January 13, 2024, a threat actor named 'zelda' leaked a database on a dark web forum containing personal information of over 1.4 million employees of the Saudi Ministry of Foreign Affairs. The compromised data includes full names, contact details, job titles, and internal employee identifiers. This represents one of the largest government data breaches in Saudi history.",
    descriptionAr: "في 13 يناير 2024، قام ممثل تهديد يُدعى 'zelda' بتسريب قاعدة بيانات على منتدى في الويب المظلم تحتوي على معلومات شخصية لأكثر من 1.4 مليون موظف في وزارة الخارجية السعودية. تتضمن البيانات المخترقة الأسماء الكاملة وتفاصيل الاتصال والمسميات الوظيفية ومعرفات الموظفين الداخلية.",
    aiSeverity: "critical",
    aiSummary: "This is an extremely high-impact breach affecting a sovereign government ministry. The exposure of 1.4M employee records creates massive risks for targeted phishing, espionage, and social engineering attacks against Saudi diplomatic personnel worldwide.",
    aiSummaryAr: "هذا اختراق شديد الخطورة يؤثر على وزارة حكومية سيادية. يخلق تعرض 1.4 مليون سجل موظف مخاطر هائلة للتصيد المستهدف والتجسس وهجمات الهندسة الاجتماعية ضد الموظفين الدبلوماسيين السعوديين في جميع أنحاء العالم.",
    aiRecommendations: JSON.stringify(["Immediate credential rotation for all MoFA employees", "Deploy advanced email security filters", "Notify affected employees with identity protection guidance", "Engage NCSC for coordinated response"]),
    aiRecommendationsAr: JSON.stringify(["تدوير فوري لبيانات اعتماد جميع موظفي الوزارة", "نشر فلاتر أمان البريد الإلكتروني المتقدمة", "إخطار الموظفين المتأثرين بإرشادات حماية الهوية", "التنسيق مع المركز الوطني للأمن السيبراني"]),
    aiConfidence: 94,
    enrichedAt: new Date("2024-01-15"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2024-01-13"),
  },
  {
    leakId: "LK-2024-0002",
    title: "Saudi Pharmaceutical Health Platform — 7 Million Patient Records",
    titleAr: "منصة صحية صيدلانية سعودية — 7 ملايين سجل مريض",
    source: "darkweb",
    severity: "critical",
    sector: "Healthcare",
    sectorAr: "صحي",
    piiTypes: JSON.stringify(["Full Name", "Phone", "Address", "Blood Type", "Medical Records", "Payment Info"]),
    recordCount: 7000000,
    status: "reported",
    description: "On May 20, 2024, a threat actor posted on an underground forum claiming access to a breached Saudi pharmaceutical health website database. The SQL-format data contains over 7 million records from 2023, including full names, phone numbers, cities, addresses, payment methods, transaction details, and sensitive medical information such as height, weight, gender, blood type, pregnancy, and breastfeeding status.",
    descriptionAr: "في 20 مايو 2024، نشر ممثل تهديد على منتدى سري يدعي الوصول إلى قاعدة بيانات مخترقة لموقع صحي صيدلاني سعودي. تحتوي البيانات بصيغة SQL على أكثر من 7 ملايين سجل من عام 2023، تشمل الأسماء الكاملة وأرقام الهواتف والمدن والعناوين وطرق الدفع وتفاصيل المعاملات ومعلومات طبية حساسة.",
    aiSeverity: "critical",
    aiSummary: "Catastrophic healthcare data breach exposing 7M patient records with highly sensitive medical and financial data. This violates PDPL Article 22 regarding health data protection and requires immediate SDAIA notification within 72 hours.",
    aiSummaryAr: "اختراق كارثي لبيانات الرعاية الصحية يكشف 7 ملايين سجل مريض مع بيانات طبية ومالية حساسة للغاية. ينتهك المادة 22 من نظام حماية البيانات الشخصية ويتطلب إخطار سدايا فوري خلال 72 ساعة.",
    aiRecommendations: JSON.stringify(["Notify SDAIA within 72 hours per PDPL", "Alert MOH and affected healthcare providers", "Engage forensic investigation team", "Monitor dark web for data resale"]),
    aiRecommendationsAr: JSON.stringify(["إخطار سدايا خلال 72 ساعة وفقاً لنظام حماية البيانات", "تنبيه وزارة الصحة ومقدمي الرعاية الصحية المتأثرين", "إشراك فريق التحقيق الجنائي", "مراقبة الويب المظلم لإعادة بيع البيانات"]),
    aiConfidence: 91,
    enrichedAt: new Date("2024-05-22"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2024-05-20"),
  },
  {
    leakId: "LK-2021-0001",
    title: "Saudi Aramco Contractor Data Leak — 1TB Extortion",
    titleAr: "تسريب بيانات مقاولي أرامكو السعودية — ابتزاز 1 تيرابايت",
    source: "darkweb",
    severity: "critical",
    sector: "Oil & Gas",
    sectorAr: "نفط وغاز",
    piiTypes: JSON.stringify(["Employee PII", "Network Maps", "Contractor Data", "Internal Documents"]),
    recordCount: 500000,
    status: "reported",
    description: "In July 2021, threat actor ZeroX leaked 1 terabyte of Saudi Aramco data on the darknet, demanding $50 million in cryptocurrency. The data was obtained through a third-party contractor and includes employee PII, network infrastructure maps, and internal corporate documents. BBC, CNBC, and Al Jazeera confirmed the breach.",
    descriptionAr: "في يوليو 2021، سرّب ممثل التهديد ZeroX تيرابايت واحد من بيانات أرامكو السعودية على الشبكة المظلمة، مطالباً بـ 50 مليون دولار بالعملة المشفرة. تم الحصول على البيانات من خلال مقاول طرف ثالث وتشمل بيانات شخصية للموظفين وخرائط البنية التحتية للشبكة ووثائق داخلية.",
    aiSeverity: "critical",
    aiSummary: "Nation-state level breach of the world's most valuable oil company. The 1TB data leak through contractor access highlights critical supply chain security failures. This incident has geopolitical implications and was covered by major international media.",
    aiSummaryAr: "اختراق على مستوى الدولة لأكبر شركة نفط في العالم. يسلط تسريب البيانات بحجم 1 تيرابايت عبر وصول المقاول الضوء على إخفاقات أمنية حرجة في سلسلة التوريد.",
    aiRecommendations: JSON.stringify(["Audit all third-party contractor access", "Implement zero-trust architecture", "Deploy DLP solutions across supply chain", "Coordinate with NCSC and NCA"]),
    aiRecommendationsAr: JSON.stringify(["تدقيق جميع أذونات وصول المقاولين", "تطبيق بنية الثقة الصفرية", "نشر حلول منع فقدان البيانات عبر سلسلة التوريد", "التنسيق مع المركز الوطني للأمن السيبراني"]),
    aiConfidence: 98,
    enrichedAt: new Date("2021-07-25"),
    region: "Eastern Province", regionAr: "المنطقة الشرقية", city: "Dhahran", cityAr: "الظهران",
    latitude: "26.2361", longitude: "50.0393",
    detectedAt: new Date("2021-07-21"),
  },
  {
    leakId: "LK-2025-0001",
    title: "Saudi Games 2024 — Athletes and Visitors Data Leak by Cyber Fattah",
    titleAr: "الألعاب السعودية 2024 — تسريب بيانات الرياضيين والزوار من قبل سايبر فتاح",
    source: "telegram",
    severity: "critical",
    sector: "Sports/Government",
    sectorAr: "رياضي/حكومي",
    piiTypes: JSON.stringify(["Passport", "National ID", "IBAN", "Medical Certificates", "Full Name", "Phone"]),
    recordCount: 45000,
    status: "documented",
    description: "On June 22, 2025, Iran-linked hacktivist group Cyber Fattah leaked thousands of records from Saudi Games 2024 via their Telegram channel. The SQL dumps, created on May 5, 2025 via phpMyAdmin, contain IT staff credentials, government officials data, athletes/visitors PII, passport scans, ID cards, bank statements, IBAN certificates, and medical examination certificates. Resecurity confirmed the breach through HUMINT engagement.",
    descriptionAr: "في 22 يونيو 2025، سرّبت مجموعة سايبر فتاح المرتبطة بإيران آلاف السجلات من الألعاب السعودية 2024 عبر قناتهم على تيليجرام. تحتوي ملفات SQL على بيانات اعتماد موظفي تقنية المعلومات وبيانات مسؤولين حكوميين ومعلومات شخصية للرياضيين والزوار وصور جوازات السفر وبطاقات الهوية وكشوف حسابات بنكية وشهادات آيبان وشهادات فحص طبي.",
    aiSeverity: "critical",
    aiSummary: "State-sponsored attack targeting a major national sports event. The combination of passport scans, IBAN certificates, and medical records creates extreme identity theft risk. The geopolitical motivation (Iran-linked) elevates this to a national security incident.",
    aiSummaryAr: "هجوم مدعوم من دولة يستهدف حدثاً رياضياً وطنياً كبيراً. يخلق الجمع بين صور جوازات السفر وشهادات الآيبان والسجلات الطبية مخاطر سرقة هوية شديدة.",
    aiRecommendations: JSON.stringify(["Notify all affected athletes and visitors immediately", "Coordinate with GIP on Iran-linked threat intelligence", "Deploy identity monitoring for affected individuals", "Strengthen phpMyAdmin security across government sites"]),
    aiRecommendationsAr: JSON.stringify(["إخطار جميع الرياضيين والزوار المتأثرين فوراً", "التنسيق مع الاستخبارات العامة بشأن التهديدات المرتبطة بإيران", "نشر مراقبة الهوية للأفراد المتأثرين", "تعزيز أمان phpMyAdmin عبر المواقع الحكومية"]),
    aiConfidence: 96,
    enrichedAt: new Date("2025-06-24"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-06-22"),
  },
  {
    leakId: "LK-2025-0002",
    title: "Saudi Recruitment Database — 150,000 Job Applicants",
    titleAr: "قاعدة بيانات توظيف سعودية — 150,000 متقدم للوظائف",
    source: "darkweb",
    severity: "critical",
    sector: "Recruitment/HR",
    sectorAr: "توظيف/موارد بشرية",
    piiTypes: JSON.stringify(["Passport Number", "Full Name", "Email", "Phone", "DOB", "Address", "Health Conditions", "CV Files"]),
    recordCount: 150000,
    status: "documented",
    description: "On September 9, 2025, a threat actor advertised the sale of a breached Saudi recruitment database on an underground forum. The database contains approximately 150,000 records including passport numbers, CV file paths, full names, emails, phone numbers, dates of birth, addresses, job preferences, health conditions, marital status, and emergency contacts. The full dataset was priced at $290 with samples shared via Pastebin.",
    descriptionAr: "في 9 سبتمبر 2025، عرض ممثل تهديد بيع قاعدة بيانات توظيف سعودية مخترقة على منتدى سري. تحتوي القاعدة على حوالي 150,000 سجل تشمل أرقام جوازات السفر ومسارات ملفات السير الذاتية والأسماء الكاملة والبريد الإلكتروني وأرقام الهواتف وتواريخ الميلاد والعناوين والحالات الصحية.",
    aiSeverity: "critical",
    aiSummary: "Highly sensitive recruitment data breach exposing passport numbers and health conditions of 150K Saudi job applicants. The low price ($290) suggests the data may already be widely distributed. Passport exposure creates severe identity fraud risk.",
    aiSummaryAr: "اختراق بيانات توظيف حساسة للغاية يكشف أرقام جوازات السفر والحالات الصحية لـ 150 ألف متقدم سعودي. السعر المنخفض يشير إلى احتمال توزيع البيانات على نطاق واسع.",
    aiRecommendations: JSON.stringify(["Alert passport authority for potential fraud monitoring", "Notify affected applicants", "Investigate recruitment platform security", "Monitor for identity fraud patterns"]),
    aiRecommendationsAr: JSON.stringify(["تنبيه هيئة الجوازات لمراقبة الاحتيال المحتمل", "إخطار المتقدمين المتأثرين", "التحقيق في أمان منصة التوظيف", "مراقبة أنماط الاحتيال في الهوية"]),
    aiConfidence: 89,
    enrichedAt: new Date("2025-09-11"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-09-09"),
  },
  // === HIGH SEVERITY ===
  {
    leakId: "LK-2024-0003",
    title: "Riyadh Airport (KKIA) Employee Data Breach — 864 Staff Records",
    titleAr: "اختراق بيانات موظفي مطار الرياض — 864 سجل موظف",
    source: "darkweb",
    severity: "high",
    sector: "Aviation",
    sectorAr: "طيران",
    piiTypes: JSON.stringify(["Employee Number", "Full Name", "Corporate Email", "Mobile Number"]),
    recordCount: 864,
    status: "reported",
    description: "In May 2024, Riyadh Airport (King Khalid International Airport) suffered a data breach impacting 864 employees. A threat actor uploaded the stolen database on a cybercrime forum on June 1, 2024. The compromised data includes employee numbers, full names, corporate email addresses, and mobile numbers.",
    descriptionAr: "في مايو 2024، تعرض مطار الرياض (مطار الملك خالد الدولي) لاختراق بيانات أثر على 864 موظفاً. قام ممثل تهديد بتحميل قاعدة البيانات المسروقة على منتدى جرائم إلكترونية في 1 يونيو 2024.",
    aiSeverity: "high",
    aiSummary: "Aviation sector breach exposing airport employee PII. While the record count is relatively small, the critical infrastructure nature of the target elevates the risk significantly. Employee data could be used for social engineering attacks against airport security.",
    aiSummaryAr: "اختراق قطاع الطيران يكشف بيانات شخصية لموظفي المطار. رغم أن عدد السجلات صغير نسبياً، إلا أن طبيعة البنية التحتية الحرجة للهدف ترفع المخاطر بشكل كبير.",
    aiRecommendations: JSON.stringify(["Reset all employee credentials", "Implement phishing awareness training", "Monitor for social engineering attempts", "Review airport access control systems"]),
    aiRecommendationsAr: JSON.stringify(["إعادة تعيين جميع بيانات اعتماد الموظفين", "تنفيذ تدريب التوعية بالتصيد", "مراقبة محاولات الهندسة الاجتماعية", "مراجعة أنظمة التحكم في الوصول للمطار"]),
    aiConfidence: 92,
    enrichedAt: new Date("2024-06-03"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.9578", longitude: "46.6989",
    detectedAt: new Date("2024-06-01"),
  },
  {
    leakId: "LK-2024-0004",
    title: "Saudi Government Health Department — Patient Records Leak",
    titleAr: "إدارة صحية حكومية سعودية — تسريب سجلات المرضى",
    source: "darkweb",
    severity: "high",
    sector: "Healthcare",
    sectorAr: "صحي",
    piiTypes: JSON.stringify(["Patient Info", "Clinical Notes", "Medical History", "National ID"]),
    recordCount: 12000,
    status: "documented",
    description: "On August 22, 2024, a threat actor leaked a database allegedly belonging to a Saudi government health department. The breach contains thousands of personal records in SQL format with UTF-8 Arabic names, including patient information, clinical notes, illness types, medical history, and personal identifiers.",
    descriptionAr: "في 22 أغسطس 2024، سرّب ممثل تهديد قاعدة بيانات يُزعم أنها تابعة لإدارة صحية حكومية سعودية. يحتوي الاختراق على آلاف السجلات الشخصية بصيغة SQL مع أسماء عربية بترميز UTF-8.",
    aiSeverity: "high",
    aiSummary: "Healthcare data breach exposing sensitive patient records including clinical notes and medical history. This data is protected under PDPL health data provisions and requires immediate regulatory notification.",
    aiSummaryAr: "اختراق بيانات صحية يكشف سجلات مرضى حساسة تشمل ملاحظات سريرية وتاريخ طبي. هذه البيانات محمية بموجب أحكام البيانات الصحية في نظام حماية البيانات الشخصية.",
    aiRecommendations: JSON.stringify(["Notify MOH and SDAIA immediately", "Identify affected patients", "Assess clinical impact of exposed records", "Strengthen database access controls"]),
    aiRecommendationsAr: JSON.stringify(["إخطار وزارة الصحة وسدايا فوراً", "تحديد المرضى المتأثرين", "تقييم التأثير السريري للسجلات المكشوفة", "تعزيز ضوابط الوصول لقاعدة البيانات"]),
    aiConfidence: 87,
    enrichedAt: new Date("2024-08-25"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2024-08-22"),
  },
  {
    leakId: "LK-2025-0003",
    title: "Saudi E-commerce Platform Admin Access Sale — 66K Customers",
    titleAr: "بيع وصول إداري لمنصة تجارة إلكترونية سعودية — 66 ألف عميل",
    source: "darkweb",
    severity: "high",
    sector: "E-commerce",
    sectorAr: "تجارة إلكترونية",
    piiTypes: JSON.stringify(["Customer Data", "Order History", "Payment Info", "Full Name", "Address"]),
    recordCount: 66000,
    status: "analyzing",
    description: "On September 8, 2025, a seller on an underground forum offered full admin panel access to a Saudi e-commerce backend. The shop has lifetime sales of ~9.7 million SAR, 66,000+ customers, and 72,000+ orders. The access was priced at $600 and includes dashboard management, customer information, order tracking, and sales analytics.",
    descriptionAr: "في 8 سبتمبر 2025، عرض بائع على منتدى سري وصولاً كاملاً للوحة إدارة متجر إلكتروني سعودي. المتجر لديه مبيعات إجمالية تقارب 9.7 مليون ريال و66,000+ عميل و72,000+ طلب. سعر الوصول 600 دولار.",
    aiSeverity: "high",
    aiSummary: "Active admin access sale for a major Saudi e-commerce platform. The combination of customer PII, payment data, and order history creates significant fraud risk. The low price suggests the seller may have already extracted valuable data.",
    aiSummaryAr: "بيع وصول إداري نشط لمنصة تجارة إلكترونية سعودية كبرى. يخلق الجمع بين بيانات العملاء الشخصية وبيانات الدفع وسجل الطلبات مخاطر احتيال كبيرة.",
    aiRecommendations: JSON.stringify(["Identify the affected e-commerce platform", "Revoke compromised admin credentials", "Notify affected customers", "Conduct security audit of the platform"]),
    aiRecommendationsAr: JSON.stringify(["تحديد منصة التجارة الإلكترونية المتأثرة", "إلغاء بيانات الاعتماد الإدارية المخترقة", "إخطار العملاء المتأثرين", "إجراء تدقيق أمني للمنصة"]),
    aiConfidence: 85,
    enrichedAt: new Date("2025-09-10"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-09-08"),
  },
  {
    leakId: "LK-2025-0004",
    title: "Saudi Government Entity SSH Access Sale",
    titleAr: "بيع وصول SSH لجهة حكومية سعودية",
    source: "darkweb",
    severity: "high",
    sector: "Government",
    sectorAr: "حكومي",
    piiTypes: JSON.stringify(["Server Access", "SSH Keys", "System Data"]),
    recordCount: 0,
    status: "analyzing",
    description: "On May 24, 2025, a forum user offered SSH key-based access to a Linux server associated with a Saudi Arabian government entity. The listing indicates unauthorized access to a critical government system, representing a significant security breach with potential for data exfiltration.",
    descriptionAr: "في 24 مايو 2025، عرض مستخدم منتدى وصول SSH عبر مفتاح لخادم Linux تابع لجهة حكومية سعودية. يشير العرض إلى وصول غير مصرح به لنظام حكومي حرج.",
    aiSeverity: "critical",
    aiSummary: "Active unauthorized access to a Saudi government server being sold on dark web. This represents an ongoing threat that could lead to further data exfiltration or system compromise.",
    aiSummaryAr: "وصول غير مصرح به نشط لخادم حكومي سعودي يُباع على الويب المظلم. يمثل تهديداً مستمراً قد يؤدي لمزيد من سرقة البيانات.",
    aiRecommendations: JSON.stringify(["Urgent: Identify the affected government entity", "Rotate all SSH keys and credentials", "Conduct forensic analysis of the server", "Implement network segmentation"]),
    aiRecommendationsAr: JSON.stringify(["عاجل: تحديد الجهة الحكومية المتأثرة", "تدوير جميع مفاتيح SSH وبيانات الاعتماد", "إجراء تحليل جنائي للخادم", "تطبيق تجزئة الشبكة"]),
    aiConfidence: 82,
    enrichedAt: new Date("2025-05-26"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-05-24"),
  },
  {
    leakId: "LK-2021-0002",
    title: "GlobeMed Saudi Healthcare Breach — 201GB Patient Data",
    titleAr: "اختراق جلوب ميد السعودية — 201 جيجابايت بيانات مرضى",
    source: "darkweb",
    severity: "high",
    sector: "Healthcare",
    sectorAr: "صحي",
    piiTypes: JSON.stringify(["Patient Name", "Credit Card", "COVID Test Results", "Medical Records", "Phone"]),
    recordCount: 350000,
    status: "reported",
    description: "In 2021, GlobeMed Saudi, a healthcare insurance support company, was breached by Xing Team. Hackers obtained 201GB of data and published half on their data leak website. The data includes patient names, phone numbers, credit cards, diagnosis on admission, COVID-19 test results, medical records, and patient condition notes.",
    descriptionAr: "في 2021، تعرضت جلوب ميد السعودية لدعم التأمين الصحي للاختراق من قبل فريق Xing. حصل القراصنة على 201 جيجابايت من البيانات ونشروا نصفها. تشمل البيانات أسماء المرضى وأرقام الهواتف وبطاقات الائتمان ونتائج فحوصات كوفيد-19 والسجلات الطبية.",
    aiSeverity: "high",
    aiSummary: "Major healthcare insurance breach with 201GB of sensitive medical and financial data. The exposure of COVID test results and credit card data creates dual medical privacy and financial fraud risks.",
    aiSummaryAr: "اختراق كبير لتأمين الرعاية الصحية مع 201 جيجابايت من البيانات الطبية والمالية الحساسة.",
    aiRecommendations: JSON.stringify(["Notify SAMA regarding credit card exposure", "Alert affected patients", "Monitor for medical identity fraud", "Implement healthcare data encryption"]),
    aiRecommendationsAr: JSON.stringify(["إخطار ساما بشأن تعرض بطاقات الائتمان", "تنبيه المرضى المتأثرين", "مراقبة الاحتيال في الهوية الطبية", "تطبيق تشفير البيانات الصحية"]),
    aiConfidence: 90,
    enrichedAt: new Date("2021-12-15"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2021-11-01"),
  },
  {
    leakId: "LK-2020-0001",
    title: "Dali Caller ID App — 5 Million Saudi Users Exposed",
    titleAr: "تطبيق دالي لتعريف المتصل — تعرض 5 ملايين مستخدم سعودي",
    source: "darkweb",
    severity: "high",
    sector: "Technology",
    sectorAr: "تقنية",
    piiTypes: JSON.stringify(["Phone Number", "Full Name", "Email", "GPS Location", "SIM Card Info", "Device Info"]),
    recordCount: 5000000,
    status: "reported",
    description: "The Dali Caller ID app suffered a massive data exposure due to a misconfigured MongoDB database. Over 585GB of data was publicly accessible, including names, gender, email addresses, professions, mobile numbers, IP addresses, SIM card details, device info, and GPS locations of more than 5 million users. A ransomware note was left in the database unnoticed.",
    descriptionAr: "تعرض تطبيق دالي لتعريف المتصل لتسريب بيانات ضخم بسبب قاعدة بيانات MongoDB غير مؤمنة. كان أكثر من 585 جيجابايت من البيانات متاحاً للعموم، تشمل الأسماء والجنس وعناوين البريد الإلكتروني والمهن وأرقام الهواتف وعناوين IP وتفاصيل بطاقات SIM ومعلومات الأجهزة ومواقع GPS لأكثر من 5 ملايين مستخدم.",
    aiSeverity: "critical",
    aiSummary: "Massive consumer data exposure affecting 5M+ Saudi users. The GPS location data combined with SIM card info creates severe stalking and surveillance risks. The misconfigured database indicates fundamental security negligence.",
    aiSummaryAr: "تعرض بيانات مستهلكين ضخم يؤثر على أكثر من 5 ملايين مستخدم سعودي. بيانات GPS مع معلومات بطاقة SIM تخلق مخاطر مراقبة وتتبع شديدة.",
    aiRecommendations: JSON.stringify(["Notify CITC about telecom data exposure", "Alert affected users", "Mandate MongoDB security audit", "Implement automated database security scanning"]),
    aiRecommendationsAr: JSON.stringify(["إخطار هيئة الاتصالات بشأن تعرض بيانات الاتصالات", "تنبيه المستخدمين المتأثرين", "فرض تدقيق أمان MongoDB", "تطبيق فحص أمان قواعد البيانات الآلي"]),
    aiConfidence: 95,
    enrichedAt: new Date("2020-06-15"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2020-05-01"),
  },
  {
    leakId: "LK-2024-0005",
    title: "Saudi Ministry of Industry & Mineral Resources — 15-Month Exposure",
    titleAr: "وزارة الصناعة والثروة المعدنية — تعرض لمدة 15 شهراً",
    source: "darkweb",
    severity: "high",
    sector: "Government",
    sectorAr: "حكومي",
    piiTypes: JSON.stringify(["API Keys", "Database Credentials", "SMTP Credentials", "System Config"]),
    recordCount: 0,
    status: "reported",
    description: "In January 2024, CyberNews researchers discovered that Saudi Arabia's Ministry of Industry and Mineral Resources (MIM) had an environment file (.env) exposed for 15 months. The file contained sensitive system details including database credentials, API keys, and SMTP configuration, potentially allowing attackers to access government systems and citizen data.",
    descriptionAr: "في يناير 2024، اكتشف باحثو CyberNews أن وزارة الصناعة والثروة المعدنية السعودية كان لديها ملف بيئة (.env) مكشوف لمدة 15 شهراً. احتوى الملف على تفاصيل نظام حساسة تشمل بيانات اعتماد قاعدة البيانات ومفاتيح API وتكوين SMTP.",
    aiSeverity: "high",
    aiSummary: "Prolonged credential exposure at a government ministry. The 15-month window means attackers had ample time to access backend systems. Database credentials could have been used to exfiltrate citizen and industrial data.",
    aiSummaryAr: "تعرض بيانات اعتماد مطول في وزارة حكومية. نافذة الـ 15 شهراً تعني أن المهاجمين كان لديهم وقت كافٍ للوصول إلى الأنظمة الخلفية.",
    aiRecommendations: JSON.stringify(["Rotate all exposed credentials immediately", "Audit access logs for the 15-month period", "Implement secrets management solution", "Deploy automated exposure scanning"]),
    aiRecommendationsAr: JSON.stringify(["تدوير جميع بيانات الاعتماد المكشوفة فوراً", "تدقيق سجلات الوصول لفترة 15 شهراً", "تطبيق حل إدارة الأسرار", "نشر فحص التعرض الآلي"]),
    aiConfidence: 93,
    enrichedAt: new Date("2024-01-12"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2024-01-08"),
  },
  {
    leakId: "LK-2020-0002",
    title: "Virgin Mobile KSA — Employee and Customer Data Sale",
    titleAr: "فيرجن موبايل السعودية — بيع بيانات الموظفين والعملاء",
    source: "darkweb",
    severity: "high",
    sector: "Telecom",
    sectorAr: "اتصالات",
    piiTypes: JSON.stringify(["Username", "Employee Name", "Email", "Activation Reports"]),
    recordCount: 1000,
    status: "reported",
    description: "In 2020, hackers breached Virgin Mobile KSA systems and offered stolen data on the dark web. The data included employee emails, activation reports, account managers' performance data, and a list of 1,000 users with usernames, employee names, and email addresses.",
    descriptionAr: "في 2020، اخترق قراصنة أنظمة فيرجن موبايل السعودية وعرضوا البيانات المسروقة على الويب المظلم. تشمل البيانات رسائل البريد الإلكتروني للموظفين وتقارير التفعيل وبيانات أداء مديري الحسابات.",
    aiSeverity: "high",
    aiSummary: "Telecom sector breach exposing employee and customer data. The activation reports could reveal customer patterns and the employee data enables targeted social engineering.",
    aiSummaryAr: "اختراق قطاع الاتصالات يكشف بيانات الموظفين والعملاء. تقارير التفعيل قد تكشف أنماط العملاء.",
    aiRecommendations: JSON.stringify(["Notify CITC", "Reset all employee credentials", "Monitor for customer fraud", "Implement DLP for telecom data"]),
    aiRecommendationsAr: JSON.stringify(["إخطار هيئة الاتصالات", "إعادة تعيين جميع بيانات اعتماد الموظفين", "مراقبة احتيال العملاء", "تطبيق منع فقدان البيانات لبيانات الاتصالات"]),
    aiConfidence: 86,
    enrichedAt: new Date("2020-08-01"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2020-07-15"),
  },
  {
    leakId: "LK-2025-0005",
    title: "MENA Delivery Platform — Saudi Customer Data Leak",
    titleAr: "منصة توصيل الشرق الأوسط — تسريب بيانات عملاء سعوديين",
    source: "darkweb",
    severity: "high",
    sector: "Logistics",
    sectorAr: "لوجستيات",
    piiTypes: JSON.stringify(["Full Name", "Email", "Password Hash", "Client ID"]),
    recordCount: 1845,
    status: "documented",
    description: "On September 13, 2025, threat actor 'privilege' leaked 1,845 user records from a delivery and shipping management platform serving Saudi Arabia. The data includes full names, verified email addresses, bcrypt-hashed passwords, avatars, client IDs, and activity timestamps with Arabic names.",
    descriptionAr: "في 13 سبتمبر 2025، سرّب ممثل التهديد 'privilege' 1,845 سجل مستخدم من منصة إدارة التوصيل والشحن التي تخدم السعودية. تشمل البيانات الأسماء الكاملة وعناوين البريد الإلكتروني المحققة وكلمات المرور المشفرة.",
    aiSeverity: "high",
    aiSummary: "Logistics platform breach exposing Saudi customer data. While bcrypt hashing provides some password protection, the email and name combination enables targeted phishing campaigns.",
    aiSummaryAr: "اختراق منصة لوجستية يكشف بيانات عملاء سعوديين. رغم أن تشفير bcrypt يوفر بعض حماية كلمات المرور، إلا أن مزيج البريد الإلكتروني والاسم يمكّن حملات التصيد المستهدفة.",
    aiRecommendations: JSON.stringify(["Notify affected Saudi customers", "Force password resets", "Monitor for credential stuffing attacks", "Audit platform security"]),
    aiRecommendationsAr: JSON.stringify(["إخطار العملاء السعوديين المتأثرين", "فرض إعادة تعيين كلمات المرور", "مراقبة هجمات حشو بيانات الاعتماد", "تدقيق أمان المنصة"]),
    aiConfidence: 88,
    enrichedAt: new Date("2025-09-15"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-09-13"),
  },
  // === MEDIUM SEVERITY ===
  {
    leakId: "LK-2019-0001",
    title: "King Saud University — Staff and Student Data Hack",
    titleAr: "جامعة الملك سعود — اختراق بيانات الموظفين والطلاب",
    source: "paste",
    severity: "medium",
    sector: "Education",
    sectorAr: "تعليم",
    piiTypes: JSON.stringify(["Full Name", "Email", "Phone", "Password"]),
    recordCount: 800,
    status: "reported",
    description: "White-hat hacker Yourikan breached King Saud University's official website, stealing data from over 800 users including staff and students. The data included names, email addresses, mobile phones, and passwords. The hacker claimed to have financial information but chose not to publish it.",
    descriptionAr: "اخترق القرصان الأخلاقي Yourikan الموقع الرسمي لجامعة الملك سعود، وسرق بيانات أكثر من 800 مستخدم من الموظفين والطلاب. تشمل البيانات الأسماء وعناوين البريد الإلكتروني وأرقام الهواتف وكلمات المرور.",
    aiSeverity: "medium",
    aiSummary: "Education sector breach by a white-hat hacker who responsibly disclosed the vulnerability. The passwords could be used for credential stuffing on other platforms where students reuse passwords.",
    aiSummaryAr: "اختراق قطاع التعليم من قبل قرصان أخلاقي كشف الثغرة بشكل مسؤول.",
    aiRecommendations: JSON.stringify(["Force password resets for all affected accounts", "Implement MFA for university systems", "Conduct web application security audit", "Establish bug bounty program"]),
    aiRecommendationsAr: JSON.stringify(["فرض إعادة تعيين كلمات المرور لجميع الحسابات المتأثرة", "تطبيق المصادقة متعددة العوامل لأنظمة الجامعة", "إجراء تدقيق أمان تطبيقات الويب", "إنشاء برنامج مكافآت الثغرات"]),
    aiConfidence: 91,
    enrichedAt: new Date("2019-04-15"),
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7249", longitude: "46.6142",
    detectedAt: new Date("2019-03-01"),
  },
  // More leaks across different regions and sectors
  {
    leakId: "LK-2025-0006",
    title: "313 Team Hacktivist Threat Against Saudi Infrastructure",
    titleAr: "تهديد فريق 313 الناشط ضد البنية التحتية السعودية",
    source: "telegram",
    severity: "high",
    sector: "Government",
    sectorAr: "حكومي",
    piiTypes: JSON.stringify(["Infrastructure Data", "DDoS Targets"]),
    recordCount: 0,
    status: "analyzing",
    description: "On August 19, 2025, hacktivist group 313 Team issued a statement condemning Saudi government policies and threatening severe cyberattacks. The group claimed collaboration with Yemen Cyber Army and other pro-Palestine/pro-Iranian organizations, suggesting coordinated multi-faction attacks on Saudi infrastructure.",
    descriptionAr: "في 19 أغسطس 2025، أصدرت مجموعة 313 Team بياناً يدين سياسات الحكومة السعودية ويهدد بهجمات إلكترونية شديدة. ادعت المجموعة التعاون مع جيش اليمن السيبراني.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-08-19"),
  },
  {
    leakId: "LK-2025-0007",
    title: "Cyber Unity — Saudi Defense Documents Leak",
    titleAr: "سايبر يونيتي — تسريب وثائق دفاعية سعودية",
    source: "telegram",
    severity: "critical",
    sector: "Defense",
    sectorAr: "دفاع",
    piiTypes: JSON.stringify(["Military Documents", "Weapons Data", "Defense Contracts"]),
    recordCount: 500,
    status: "analyzing",
    description: "On August 17, 2025, a Telegram channel called Cyber Unity began releasing sensitive documents related to weaponry, including files suggesting Saudi Arabia's involvement. The leaked materials comprise PDFs and classified defense-related documents.",
    descriptionAr: "في 17 أغسطس 2025، بدأت قناة تيليجرام تُدعى سايبر يونيتي بنشر وثائق حساسة تتعلق بالأسلحة، تشمل ملفات تشير إلى تورط المملكة العربية السعودية.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-08-17"),
  },
  {
    leakId: "LK-2016-0001",
    title: "Shamoon 2.0 — SAMA and Government Agencies Disk Wipe Attack",
    titleAr: "شمعون 2.0 — هجوم مسح أقراص على ساما والجهات الحكومية",
    source: "darkweb",
    severity: "critical",
    sector: "Banking/Government",
    sectorAr: "مصرفي/حكومي",
    piiTypes: JSON.stringify(["System Data", "Financial Records", "Employee Data"]),
    recordCount: 35000,
    status: "reported",
    description: "Iran state-sponsored hackers used Shamoon malware to attack SAMA (Saudi Arabian Monetary Agency), General Authority of Civil Aviation, Ministry of Transportation, and at least 4 other government bodies. The virus deleted critical data and forced the General Authority of Civil Aviation to halt operations for several days. Over 35,000 workstations were destroyed across multiple agencies.",
    descriptionAr: "استخدم قراصنة مدعومون من إيران برنامج شمعون الخبيث لمهاجمة مؤسسة النقد العربي السعودي (ساما) والهيئة العامة للطيران المدني ووزارة النقل وما لا يقل عن 4 جهات حكومية أخرى. حذف الفيروس بيانات حرجة وأوقف عمليات الهيئة العامة للطيران المدني لعدة أيام.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2016-11-17"),
  },
  {
    leakId: "LK-2025-0008",
    title: "DragonForce Ransomware — Riyadh Real Estate Company",
    titleAr: "برنامج فدية DragonForce — شركة عقارات في الرياض",
    source: "darkweb",
    severity: "high",
    sector: "Real Estate",
    sectorAr: "عقارات",
    piiTypes: JSON.stringify(["Employee Data", "Financial Records", "Client Contracts"]),
    recordCount: 25000,
    status: "documented",
    description: "In January 2025, DragonForce ransomware group targeted a major Riyadh real estate and construction company. The group encrypted critical systems and exfiltrated employee data, financial records, and client contracts before deploying ransomware.",
    descriptionAr: "في يناير 2025، استهدفت مجموعة DragonForce للفدية شركة عقارات وبناء كبرى في الرياض. قامت المجموعة بتشفير الأنظمة الحرجة وسرقة بيانات الموظفين والسجلات المالية وعقود العملاء.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-01-15"),
  },
  {
    leakId: "LK-2026-0001",
    title: "Arabian Health Care Supply — Database Access Sale",
    titleAr: "شركة الإمداد الصحي العربية — بيع وصول لقاعدة البيانات",
    source: "darkweb",
    severity: "high",
    sector: "Healthcare",
    sectorAr: "صحي",
    piiTypes: JSON.stringify(["Patient Data", "Supply Chain Data", "Employee Records"]),
    recordCount: 80000,
    status: "new",
    description: "In January 2026, threat actor B4baYega offered database access and CSV exports from Arabian Health Care Supply on a dark web forum. The data includes patient-related supply chain information, employee records, and healthcare logistics data.",
    descriptionAr: "في يناير 2026، عرض ممثل التهديد B4baYega وصولاً لقاعدة بيانات وتصدير CSV من شركة الإمداد الصحي العربية على منتدى في الويب المظلم.",
    region: "Jeddah", regionAr: "جدة", city: "Jeddah", cityAr: "جدة",
    latitude: "21.4858", longitude: "39.1925",
    detectedAt: new Date("2026-01-10"),
  },
  {
    leakId: "LK-2025-0009",
    title: "Saudi Airport Operator Confidential Data Leak",
    titleAr: "تسريب بيانات سرية لمشغل مطار سعودي",
    source: "darkweb",
    severity: "high",
    sector: "Aviation",
    sectorAr: "طيران",
    piiTypes: JSON.stringify(["Employee Data", "Operational Data", "Security Protocols"]),
    recordCount: 5000,
    status: "documented",
    description: "In November 2025, confidential data from a Saudi Arabian airport operator was leaked on the dark web. The data includes operational information, employee records, and security-related documentation.",
    descriptionAr: "في نوفمبر 2025، تم تسريب بيانات سرية من مشغل مطار سعودي على الويب المظلم. تشمل البيانات معلومات تشغيلية وسجلات موظفين ووثائق أمنية.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.9578", longitude: "46.6989",
    detectedAt: new Date("2025-11-20"),
  },
  {
    leakId: "LK-2025-0010",
    title: "Tatweer Buildings Company Data Breach",
    titleAr: "اختراق بيانات شركة تطوير للمباني",
    source: "darkweb",
    severity: "medium",
    sector: "Construction",
    sectorAr: "بناء وتشييد",
    piiTypes: JSON.stringify(["Employee Data", "Project Documents", "Financial Records"]),
    recordCount: 15000,
    status: "documented",
    description: "In July 2025, Tatweer Buildings Company, a Saudi construction firm, suffered a data breach. The compromised data includes employee information, project documentation, and financial records.",
    descriptionAr: "في يوليو 2025، تعرضت شركة تطوير للمباني السعودية لاختراق بيانات. تشمل البيانات المخترقة معلومات الموظفين ووثائق المشاريع والسجلات المالية.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-07-15"),
  },
  // === Additional Saudi-specific incidents across regions ===
  {
    leakId: "LK-2025-0011",
    title: "Jeddah Hospital Network — Patient Records on Telegram",
    titleAr: "شبكة مستشفيات جدة — سجلات مرضى على تيليجرام",
    source: "telegram",
    severity: "critical",
    sector: "Healthcare",
    sectorAr: "صحي",
    piiTypes: JSON.stringify(["National ID", "Patient Records", "Medical History", "Insurance Data"]),
    recordCount: 230000,
    status: "documented",
    description: "A Telegram channel shared SQL dumps containing 230,000 patient records from a Jeddah hospital network. The data includes Saudi national IDs, detailed medical histories, insurance policy numbers, and treatment records spanning 2020-2024.",
    descriptionAr: "شاركت قناة تيليجرام ملفات SQL تحتوي على 230,000 سجل مريض من شبكة مستشفيات جدة. تشمل البيانات أرقام الهوية الوطنية السعودية والتاريخ الطبي المفصل وأرقام وثائق التأمين وسجلات العلاج.",
    region: "Makkah", regionAr: "مكة المكرمة", city: "Jeddah", cityAr: "جدة",
    latitude: "21.4858", longitude: "39.1925",
    detectedAt: new Date("2025-03-12"),
  },
  {
    leakId: "LK-2025-0012",
    title: "Eastern Province Petrochemical Company — Employee Database",
    titleAr: "شركة بتروكيماويات المنطقة الشرقية — قاعدة بيانات الموظفين",
    source: "darkweb",
    severity: "high",
    sector: "Oil & Gas",
    sectorAr: "نفط وغاز",
    piiTypes: JSON.stringify(["Employee ID", "Full Name", "Salary", "Bank Account", "Iqama Number"]),
    recordCount: 8500,
    status: "analyzing",
    description: "Employee database from a major petrochemical company in the Eastern Province was found on a dark web marketplace. The data includes employee IDs, full names, salary information, bank account details, and Iqama numbers for expatriate workers.",
    descriptionAr: "تم العثور على قاعدة بيانات موظفين من شركة بتروكيماويات كبرى في المنطقة الشرقية على سوق في الويب المظلم. تشمل البيانات أرقام الموظفين والأسماء الكاملة ومعلومات الرواتب وتفاصيل الحسابات البنكية وأرقام الإقامة.",
    region: "Eastern Province", regionAr: "المنطقة الشرقية", city: "Jubail", cityAr: "الجبيل",
    latitude: "27.0046", longitude: "49.6225",
    detectedAt: new Date("2025-04-18"),
  },
  {
    leakId: "LK-2025-0013",
    title: "Dammam University Student Records Paste",
    titleAr: "سجلات طلاب جامعة الدمام على موقع لصق",
    source: "paste",
    severity: "medium",
    sector: "Education",
    sectorAr: "تعليم",
    piiTypes: JSON.stringify(["Student ID", "Full Name", "GPA", "Email", "Phone"]),
    recordCount: 12500,
    status: "documented",
    description: "Student records from a Dammam-area university were posted on Pastebin, including student IDs, full names, GPAs, email addresses, and phone numbers. The data appears to span multiple academic years.",
    descriptionAr: "تم نشر سجلات طلاب من جامعة في منطقة الدمام على Pastebin، تشمل أرقام الطلاب والأسماء الكاملة والمعدلات التراكمية وعناوين البريد الإلكتروني وأرقام الهواتف.",
    region: "Eastern Province", regionAr: "المنطقة الشرقية", city: "Dammam", cityAr: "الدمام",
    latitude: "26.4207", longitude: "50.0888",
    detectedAt: new Date("2025-02-28"),
  },
  {
    leakId: "LK-2024-0006",
    title: "Madinah Hotel Chain — Guest Database Breach",
    titleAr: "سلسلة فنادق المدينة المنورة — اختراق قاعدة بيانات النزلاء",
    source: "darkweb",
    severity: "high",
    sector: "Hospitality",
    sectorAr: "ضيافة",
    piiTypes: JSON.stringify(["Passport", "Full Name", "Credit Card", "Phone", "Nationality"]),
    recordCount: 180000,
    status: "reported",
    description: "A dark web listing offered a database from a Madinah hotel chain containing 180,000 guest records including passport details, credit card information, phone numbers, and nationality data from pilgrims and tourists.",
    descriptionAr: "عرض إعلان على الويب المظلم قاعدة بيانات من سلسلة فنادق في المدينة المنورة تحتوي على 180,000 سجل نزيل تشمل تفاصيل جوازات السفر ومعلومات بطاقات الائتمان وأرقام الهواتف وبيانات الجنسية.",
    region: "Madinah", regionAr: "المدينة المنورة", city: "Madinah", cityAr: "المدينة المنورة",
    latitude: "24.4672", longitude: "39.6024",
    detectedAt: new Date("2024-11-05"),
  },
  {
    leakId: "LK-2024-0007",
    title: "Makkah Hajj Services — Pilgrim Registration Data",
    titleAr: "خدمات حج مكة — بيانات تسجيل الحجاج",
    source: "telegram",
    severity: "critical",
    sector: "Religious Services",
    sectorAr: "خدمات دينية",
    piiTypes: JSON.stringify(["Passport", "National ID", "Full Name", "Phone", "Health Records", "Visa Data"]),
    recordCount: 320000,
    status: "reported",
    description: "A Telegram channel leaked pilgrim registration data from a Hajj services provider in Makkah. The data includes passport information, national IDs, health screening records, visa details, and accommodation assignments for approximately 320,000 pilgrims.",
    descriptionAr: "سرّبت قناة تيليجرام بيانات تسجيل الحجاج من مزود خدمات حج في مكة المكرمة. تشمل البيانات معلومات جوازات السفر وأرقام الهوية الوطنية وسجلات الفحص الصحي وتفاصيل التأشيرات وتخصيصات الإقامة.",
    region: "Makkah", regionAr: "مكة المكرمة", city: "Makkah", cityAr: "مكة المكرمة",
    latitude: "21.3891", longitude: "39.8579",
    detectedAt: new Date("2024-09-15"),
  },
  {
    leakId: "LK-2025-0014",
    title: "Tabuk Military Base — Personnel Files Leak",
    titleAr: "قاعدة تبوك العسكرية — تسريب ملفات الأفراد",
    source: "darkweb",
    severity: "critical",
    sector: "Military",
    sectorAr: "عسكري",
    piiTypes: JSON.stringify(["Military ID", "Full Name", "Rank", "Unit Assignment", "Address"]),
    recordCount: 3200,
    status: "analyzing",
    description: "Personnel files from a military installation in the Tabuk region were discovered on a dark web forum. The data includes military IDs, full names, ranks, unit assignments, and residential addresses of military personnel.",
    descriptionAr: "تم اكتشاف ملفات أفراد من منشأة عسكرية في منطقة تبوك على منتدى في الويب المظلم. تشمل البيانات الهويات العسكرية والأسماء الكاملة والرتب وتعيينات الوحدات والعناوين السكنية.",
    region: "Tabuk", regionAr: "تبوك", city: "Tabuk", cityAr: "تبوك",
    latitude: "28.3838", longitude: "36.5550",
    detectedAt: new Date("2025-05-10"),
  },
  {
    leakId: "LK-2024-0008",
    title: "Abha Regional Hospital — COVID-19 Patient Database",
    titleAr: "مستشفى أبها الإقليمي — قاعدة بيانات مرضى كوفيد-19",
    source: "paste",
    severity: "high",
    sector: "Healthcare",
    sectorAr: "صحي",
    piiTypes: JSON.stringify(["National ID", "Full Name", "COVID Status", "Phone", "Address"]),
    recordCount: 45000,
    status: "documented",
    description: "A paste site contained COVID-19 patient records from a regional hospital in Abha. The data includes national IDs, full names, COVID test results, vaccination status, phone numbers, and residential addresses.",
    descriptionAr: "احتوى موقع لصق على سجلات مرضى كوفيد-19 من مستشفى إقليمي في أبها. تشمل البيانات أرقام الهوية الوطنية والأسماء الكاملة ونتائج فحوصات كوفيد وحالة التطعيم وأرقام الهواتف والعناوين السكنية.",
    region: "Asir", regionAr: "عسير", city: "Abha", cityAr: "أبها",
    latitude: "18.2164", longitude: "42.5053",
    detectedAt: new Date("2024-07-22"),
  },
  {
    leakId: "LK-2025-0015",
    title: "NEOM Project — Contractor Employee Records",
    titleAr: "مشروع نيوم — سجلات موظفي المقاولين",
    source: "darkweb",
    severity: "high",
    sector: "Construction/Mega Projects",
    sectorAr: "بناء/مشاريع عملاقة",
    piiTypes: JSON.stringify(["Iqama Number", "Full Name", "Passport", "Salary", "Bank Account"]),
    recordCount: 42000,
    status: "analyzing",
    description: "Employee records from NEOM project contractors were found on a dark web marketplace. The data includes Iqama numbers, passport details, salary information, and bank account details for approximately 42,000 construction workers and engineers.",
    descriptionAr: "تم العثور على سجلات موظفين من مقاولي مشروع نيوم على سوق في الويب المظلم. تشمل البيانات أرقام الإقامة وتفاصيل جوازات السفر ومعلومات الرواتب وتفاصيل الحسابات البنكية لحوالي 42,000 عامل ومهندس.",
    region: "Tabuk", regionAr: "تبوك", city: "NEOM", cityAr: "نيوم",
    latitude: "27.9500", longitude: "35.3000",
    detectedAt: new Date("2025-06-05"),
  },
  {
    leakId: "LK-2024-0009",
    title: "Qassim Agricultural Cooperative — Member Database",
    titleAr: "تعاونية القصيم الزراعية — قاعدة بيانات الأعضاء",
    source: "paste",
    severity: "low",
    sector: "Agriculture",
    sectorAr: "زراعة",
    piiTypes: JSON.stringify(["Full Name", "Phone", "Address", "Farm Location"]),
    recordCount: 3500,
    status: "documented",
    description: "Member database from a Qassim agricultural cooperative was found on a paste site. The data includes farmer names, phone numbers, addresses, and farm location coordinates.",
    descriptionAr: "تم العثور على قاعدة بيانات أعضاء من تعاونية زراعية في القصيم على موقع لصق. تشمل البيانات أسماء المزارعين وأرقام الهواتف والعناوين وإحداثيات مواقع المزارع.",
    region: "Qassim", regionAr: "القصيم", city: "Buraydah", cityAr: "بريدة",
    latitude: "26.3260", longitude: "43.9750",
    detectedAt: new Date("2024-03-10"),
  },
  {
    leakId: "LK-2025-0016",
    title: "Hail Region Municipality — Citizen Services Database",
    titleAr: "أمانة منطقة حائل — قاعدة بيانات خدمات المواطنين",
    source: "darkweb",
    severity: "medium",
    sector: "Government",
    sectorAr: "حكومي",
    piiTypes: JSON.stringify(["National ID", "Full Name", "Address", "Phone", "Service Requests"]),
    recordCount: 28000,
    status: "documented",
    description: "A database from the Hail Region Municipality citizen services portal was found on a dark web forum. The data includes national IDs, full names, addresses, phone numbers, and citizen service request details.",
    descriptionAr: "تم العثور على قاعدة بيانات من بوابة خدمات المواطنين لأمانة منطقة حائل على منتدى في الويب المظلم. تشمل البيانات أرقام الهوية الوطنية والأسماء الكاملة والعناوين وأرقام الهواتف.",
    region: "Hail", regionAr: "حائل", city: "Hail", cityAr: "حائل",
    latitude: "27.5114", longitude: "41.7208",
    detectedAt: new Date("2025-01-25"),
  },
  {
    leakId: "LK-2024-0010",
    title: "Jazan Border Hospital — Refugee Health Records",
    titleAr: "مستشفى جازان الحدودي — سجلات صحية للاجئين",
    source: "telegram",
    severity: "high",
    sector: "Healthcare",
    sectorAr: "صحي",
    piiTypes: JSON.stringify(["Full Name", "Nationality", "Health Records", "Biometric Data"]),
    recordCount: 15000,
    status: "documented",
    description: "Health records from a border hospital in the Jazan region were shared on a Telegram channel. The data includes names, nationalities, health screening results, and biometric data for border crossers and refugees.",
    descriptionAr: "تم مشاركة سجلات صحية من مستشفى حدودي في منطقة جازان على قناة تيليجرام. تشمل البيانات الأسماء والجنسيات ونتائج الفحص الصحي والبيانات البيومترية.",
    region: "Jazan", regionAr: "جازان", city: "Jazan", cityAr: "جازان",
    latitude: "16.8892", longitude: "42.5611",
    detectedAt: new Date("2024-12-08"),
  },
  {
    leakId: "LK-2025-0017",
    title: "Al Baha Tourism Authority — Visitor Registration Data",
    titleAr: "هيئة السياحة بالباحة — بيانات تسجيل الزوار",
    source: "paste",
    severity: "low",
    sector: "Tourism",
    sectorAr: "سياحة",
    piiTypes: JSON.stringify(["Full Name", "Phone", "Email", "Nationality"]),
    recordCount: 8000,
    status: "documented",
    description: "Visitor registration data from Al Baha tourism authority was found on a paste site. The data includes names, phone numbers, email addresses, and nationalities of tourists who registered for local attractions.",
    descriptionAr: "تم العثور على بيانات تسجيل زوار من هيئة السياحة بالباحة على موقع لصق. تشمل البيانات الأسماء وأرقام الهواتف وعناوين البريد الإلكتروني وجنسيات السياح.",
    region: "Al Baha", regionAr: "الباحة", city: "Al Baha", cityAr: "الباحة",
    latitude: "20.0000", longitude: "41.4667",
    detectedAt: new Date("2025-08-03"),
  },
  {
    leakId: "LK-2024-0011",
    title: "Najran University — Faculty and Staff Records",
    titleAr: "جامعة نجران — سجلات أعضاء هيئة التدريس والموظفين",
    source: "darkweb",
    severity: "medium",
    sector: "Education",
    sectorAr: "تعليم",
    piiTypes: JSON.stringify(["Full Name", "Email", "Phone", "Salary", "National ID"]),
    recordCount: 4200,
    status: "documented",
    description: "Faculty and staff records from Najran University were found on a dark web forum. The data includes full names, email addresses, phone numbers, salary details, and national IDs.",
    descriptionAr: "تم العثور على سجلات أعضاء هيئة التدريس والموظفين من جامعة نجران على منتدى في الويب المظلم. تشمل البيانات الأسماء الكاملة وعناوين البريد الإلكتروني وأرقام الهواتف وتفاصيل الرواتب وأرقام الهوية الوطنية.",
    region: "Najran", regionAr: "نجران", city: "Najran", cityAr: "نجران",
    latitude: "17.4917", longitude: "44.1322",
    detectedAt: new Date("2024-05-15"),
  },
  {
    leakId: "LK-2025-0018",
    title: "Northern Borders Region — Government Employee Payroll Leak",
    titleAr: "منطقة الحدود الشمالية — تسريب كشوف رواتب الموظفين الحكوميين",
    source: "darkweb",
    severity: "high",
    sector: "Government",
    sectorAr: "حكومي",
    piiTypes: JSON.stringify(["National ID", "Full Name", "Salary", "Bank Account", "IBAN"]),
    recordCount: 6800,
    status: "analyzing",
    description: "Government employee payroll data from the Northern Borders region was found on a dark web marketplace. The data includes national IDs, full names, salary breakdowns, bank account numbers, and IBAN details.",
    descriptionAr: "تم العثور على بيانات كشوف رواتب الموظفين الحكوميين من منطقة الحدود الشمالية على سوق في الويب المظلم. تشمل البيانات أرقام الهوية الوطنية والأسماء الكاملة وتفصيل الرواتب وأرقام الحسابات البنكية.",
    region: "Northern Borders", regionAr: "الحدود الشمالية", city: "Arar", cityAr: "عرعر",
    latitude: "30.9753", longitude: "41.0381",
    detectedAt: new Date("2025-03-22"),
  },
  {
    leakId: "LK-2024-0012",
    title: "Al Jouf Region Water Authority — Customer Database",
    titleAr: "هيئة مياه منطقة الجوف — قاعدة بيانات العملاء",
    source: "paste",
    severity: "low",
    sector: "Utilities",
    sectorAr: "مرافق",
    piiTypes: JSON.stringify(["Full Name", "Address", "Phone", "Account Number"]),
    recordCount: 22000,
    status: "documented",
    description: "Customer database from the Al Jouf Region Water Authority was found on a paste site. The data includes customer names, addresses, phone numbers, and water service account numbers.",
    descriptionAr: "تم العثور على قاعدة بيانات عملاء من هيئة مياه منطقة الجوف على موقع لصق. تشمل البيانات أسماء العملاء والعناوين وأرقام الهواتف وأرقام حسابات خدمة المياه.",
    region: "Al Jouf", regionAr: "الجوف", city: "Sakaka", cityAr: "سكاكا",
    latitude: "29.9697", longitude: "40.2064",
    detectedAt: new Date("2024-08-18"),
  },
  {
    leakId: "LK-2025-0019",
    title: "Saudi Fintech Startup — Customer Financial Data",
    titleAr: "شركة تقنية مالية سعودية ناشئة — بيانات مالية للعملاء",
    source: "darkweb",
    severity: "critical",
    sector: "Fintech",
    sectorAr: "تقنية مالية",
    piiTypes: JSON.stringify(["National ID", "Full Name", "IBAN", "Transaction History", "Phone"]),
    recordCount: 95000,
    status: "documented",
    description: "Customer financial data from a Saudi fintech startup was found on a dark web forum. The data includes national IDs, full names, IBAN numbers, transaction histories, and phone numbers for approximately 95,000 customers.",
    descriptionAr: "تم العثور على بيانات مالية للعملاء من شركة تقنية مالية سعودية ناشئة على منتدى في الويب المظلم. تشمل البيانات أرقام الهوية الوطنية والأسماء الكاملة وأرقام الآيبان وسجلات المعاملات.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-10-12"),
  },
  {
    leakId: "LK-2025-0020",
    title: "Yanbu Industrial City — Worker Safety Records",
    titleAr: "مدينة ينبع الصناعية — سجلات سلامة العمال",
    source: "paste",
    severity: "medium",
    sector: "Industrial",
    sectorAr: "صناعي",
    piiTypes: JSON.stringify(["Iqama Number", "Full Name", "Health Records", "Employer"]),
    recordCount: 18000,
    status: "documented",
    description: "Worker safety and health records from Yanbu Industrial City were found on a paste site. The data includes Iqama numbers, full names, health screening results, and employer details for industrial workers.",
    descriptionAr: "تم العثور على سجلات سلامة وصحة العمال من مدينة ينبع الصناعية على موقع لصق. تشمل البيانات أرقام الإقامة والأسماء الكاملة ونتائج الفحص الصحي وتفاصيل أصحاب العمل.",
    region: "Madinah", regionAr: "المدينة المنورة", city: "Yanbu", cityAr: "ينبع",
    latitude: "24.0895", longitude: "38.0618",
    detectedAt: new Date("2025-04-30"),
  },
  {
    leakId: "LK-2025-0021",
    title: "Saudi Private School Network — Student and Parent Data",
    titleAr: "شبكة مدارس خاصة سعودية — بيانات الطلاب وأولياء الأمور",
    source: "telegram",
    severity: "high",
    sector: "Education",
    sectorAr: "تعليم",
    piiTypes: JSON.stringify(["National ID", "Full Name", "Phone", "Address", "Student Records"]),
    recordCount: 55000,
    status: "analyzing",
    description: "Student and parent data from a Saudi private school network was shared on a Telegram channel. The data includes national IDs, full names, phone numbers, addresses, and academic records for approximately 55,000 students and their parents.",
    descriptionAr: "تم مشاركة بيانات الطلاب وأولياء الأمور من شبكة مدارس خاصة سعودية على قناة تيليجرام. تشمل البيانات أرقام الهوية الوطنية والأسماء الكاملة وأرقام الهواتف والعناوين والسجلات الأكاديمية.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-09-20"),
  },
  {
    leakId: "LK-2024-0013",
    title: "Khobar Insurance Company — Policy Holder Database",
    titleAr: "شركة تأمين الخبر — قاعدة بيانات حاملي الوثائق",
    source: "darkweb",
    severity: "high",
    sector: "Insurance",
    sectorAr: "تأمين",
    piiTypes: JSON.stringify(["National ID", "Full Name", "Phone", "Policy Details", "Vehicle Info"]),
    recordCount: 120000,
    status: "reported",
    description: "Policy holder database from an insurance company in Khobar was found on a dark web forum. The data includes national IDs, full names, phone numbers, insurance policy details, and vehicle information for approximately 120,000 customers.",
    descriptionAr: "تم العثور على قاعدة بيانات حاملي وثائق التأمين من شركة تأمين في الخبر على منتدى في الويب المظلم. تشمل البيانات أرقام الهوية الوطنية والأسماء الكاملة وأرقام الهواتف وتفاصيل وثائق التأمين ومعلومات المركبات.",
    region: "Eastern Province", regionAr: "المنطقة الشرقية", city: "Khobar", cityAr: "الخبر",
    latitude: "26.2172", longitude: "50.1971",
    detectedAt: new Date("2024-10-05"),
  },
  {
    leakId: "LK-2025-0022",
    title: "Saudi Ride-Hailing Platform — Driver and Rider Data",
    titleAr: "منصة نقل تشاركي سعودية — بيانات السائقين والركاب",
    source: "darkweb",
    severity: "high",
    sector: "Transportation",
    sectorAr: "نقل",
    piiTypes: JSON.stringify(["National ID", "Full Name", "Phone", "GPS Locations", "Payment Info"]),
    recordCount: 280000,
    status: "analyzing",
    description: "Driver and rider data from a Saudi ride-hailing platform was found on a dark web marketplace. The data includes national IDs, full names, phone numbers, trip GPS locations, and payment information for approximately 280,000 users.",
    descriptionAr: "تم العثور على بيانات السائقين والركاب من منصة نقل تشاركي سعودية على سوق في الويب المظلم. تشمل البيانات أرقام الهوية الوطنية والأسماء الكاملة وأرقام الهواتف ومواقع GPS للرحلات ومعلومات الدفع.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-11-08"),
  },
  {
    leakId: "LK-2025-0023",
    title: "Everest Ransomware — Saudi Retail Chain Attack",
    titleAr: "فدية Everest — هجوم على سلسلة تجزئة سعودية",
    source: "darkweb",
    severity: "high",
    sector: "Retail",
    sectorAr: "تجزئة",
    piiTypes: JSON.stringify(["Customer Data", "Payment Info", "Employee Records", "Loyalty Program"]),
    recordCount: 450000,
    status: "documented",
    description: "Everest ransomware group, the most active ransomware group in Saudi Arabia in 2025, attacked a major Saudi retail chain. The group exfiltrated customer data, payment information, employee records, and loyalty program details before deploying ransomware.",
    descriptionAr: "هاجمت مجموعة Everest للفدية، الأكثر نشاطاً في السعودية عام 2025، سلسلة تجزئة سعودية كبرى. سرقت المجموعة بيانات العملاء ومعلومات الدفع وسجلات الموظفين وتفاصيل برنامج الولاء.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-07-20"),
  },
  {
    leakId: "LK-2025-0024",
    title: "Qilin Ransomware — Saudi Healthcare Provider",
    titleAr: "فدية Qilin — مزود رعاية صحية سعودي",
    source: "darkweb",
    severity: "critical",
    sector: "Healthcare",
    sectorAr: "صحي",
    piiTypes: JSON.stringify(["Patient Records", "National ID", "Medical History", "Insurance Data"]),
    recordCount: 175000,
    status: "analyzing",
    description: "Qilin ransomware group attacked a Saudi healthcare provider, encrypting patient management systems and exfiltrating 175,000 patient records including national IDs, medical histories, and insurance data.",
    descriptionAr: "هاجمت مجموعة Qilin للفدية مزود رعاية صحية سعودي، وشفرت أنظمة إدارة المرضى وسرقت 175,000 سجل مريض تشمل أرقام الهوية الوطنية والتاريخ الطبي وبيانات التأمين.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-08-25"),
  },
  {
    leakId: "LK-2025-0025",
    title: "KillSecurity — Saudi Government Contractor Data",
    titleAr: "KillSecurity — بيانات مقاول حكومي سعودي",
    source: "darkweb",
    severity: "high",
    sector: "Government/IT",
    sectorAr: "حكومي/تقنية معلومات",
    piiTypes: JSON.stringify(["Employee Data", "Project Documents", "Access Credentials"]),
    recordCount: 35000,
    status: "documented",
    description: "KillSecurity ransomware group targeted a Saudi government IT contractor, exfiltrating employee data, project documentation, and access credentials for government systems.",
    descriptionAr: "استهدفت مجموعة KillSecurity للفدية مقاول تقنية معلومات حكومي سعودي، وسرقت بيانات الموظفين ووثائق المشاريع وبيانات اعتماد الوصول لأنظمة حكومية.",
    region: "Riyadh", regionAr: "الرياض", city: "Riyadh", cityAr: "الرياض",
    latitude: "24.7136", longitude: "46.6753",
    detectedAt: new Date("2025-06-10"),
  },
];
